version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: showroom-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
